accelerate launch --num_processes 1 qlora.py \
    --model_name_or_path /root/autodl-tmp/llama-2-13b-chat \
    --output_dir /root/autodl-tmp/llama-2-13b-chat-qlora \
    --dataset /root/autodl-tmp/data/train_data.json \
    --dataset_format fastchat-llama-2 \
    --bits 4 \
    --do_train True \
    --do_eval True \
    --source_max_len 512 \
    --target_max_len 512 \
    --dataloader_num_workers 3 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 2 \
    --logging_steps 10 \
    --max_steps 100 \
    --save_strategy steps \
    --data_seed 42 \
    --save_steps 10 \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_dataset_size 512 \
    --max_eval_samples 10 \
    --eval_steps 10 \
    --optim paged_adamw_32bit
